### ISSUE TITLE
why using so many threads

### ISSUE THREAD

**Issue by walkerlala** [IAIK/meltdown#29]
I read through the code and there is one point I cannot understand: why using many threads when performing flush_reload ? For example, in function  `libkdump_read_tsx()`:

```
int __attribute__((optimize("-Os"), noinline)) libkdump_read_tsx() {
#ifndef NO_TSX
  size_t retries = config.retries + 1;
  uint64_t start = 0, end = 0;

  while (retries--) {
    if (xbegin() == _XBEGIN_STARTED) {
      MELTDOWN;
      xend();
    }
    int i;
    for (i = 0; i < 256; i++) {
      if (flush_reload(mem + i * 4096)) {
        if (i >= 1) {
          return i;
        }
      }
      sched_yield();
    }
    sched_yield();
  }
#endif
  return 0;
}
```
what are those `sched_yield()` for?

**Comment by misc0110** [comment]
This is only one thread. The sched_yield() just tells the operating system that the current thread is done and a different thread can instead run on this CPU core (see e.g. http://man7.org/linux/man-pages/man2/sched_yield.2.html). It also works without the sched_yield, however, there is a practical reason to use it: If you voluntarily give up processing time at these well-defined points, you increase the chance that the scheduler will not interrupt you at any other, timing-critical point in your program. Because if the scheduler interrupts you during Flush+Reload, your timings will be wrong and you'd have to repeat the measurement.

**Comment by walkerlala** [comment]
> This is only one thread

If using auto-config, `load_threads` would be 1. However, if `load_threads` is not equal to 1, then in `libkdump_init()` we will use `pthread_create` to create a bunch of threads.

**Comment by misc0110** [comment]
Yes, a higher number of threads increases the success probability on some machines. However, these load threads don't do anything other than keeping the CPU busy. The Meltdown function is only run by one thread.

**Comment by walkerlala** [comment]
On Sat, Jan 13, 2018 at 04:14:51AM -0800, Michael Schwarz wrote:
> Yes, a higher number of threads increases the success probability on some machines. However, these load threads don't do anything other than keeping the CPU busy. The Meltdown function is only run by one thread. 

I still cannot see why a higher number of threads increase the success probability. What we want to is for the meltdown thread to win more time to run. However, with more threads, the probability that the meltdown thread have a chance to run is lower.
