### ISSUE TITLE
the ./physical_reader is mostly broken - only data a process is reading in a while(1) loop can be attacked

### ISSUE THREAD

**Issue by pRiVi** [IAIK/meltdown#9]
If a process is not accessing the memory to be attacked in an endless loop all the time, the memory is just not readable by meltdown! 

Try the following patch, where the secret is accessed "only" every second and not as fast as possible: it is now just not readable by meltdown!

The meltdown document is not talking about this BIG issue at all, which is realy a mess!

For more details see: https://blog.fefe.de/?ts=a4ad9f54

```
--- a/secret.c
+++ b/secret.c
@@ -15,6 +15,8 @@ const char *strings[] = {
     "Don't panic... But your CPU is broken and your data is not safe",
     "How can you read this? You should not read this!"};
 
+struct timeval tv;
+
 int main(int argc, char *argv[]) {
   libkdump_config_t config;
   config = libkdump_get_autoconfig();
@@ -36,12 +38,10 @@ int main(int argc, char *argv[]) {
   printf("\x1b[32;1m[+]\x1b[0m Physical address of secret: \x1b[32;1m0x%zx\x1b[0m\n", paddr);
   printf("\x1b[32;1m[+]\x1b[0m Exit with \x1b[37;1mCtrl+C\x1b[0m if you are done reading the secret\n");
   while (1) {
-    // keep string cached for better results
-    volatile size_t dummy = 0, i;
-    for (i = 0; i < len; i++) {
-      dummy += secret[i];
-    }
-    sched_yield();
+    printf("%s\n", secret);
+    tv.tv_sec = 1;
+    tv.tv_usec = 0;
+    select(0,0,0,0,&tv);
   }
 
   libkdump_cleanup();
```

**Comment by misc0110** [comment]
We can definitely read data which is not in L1, even uncached data. 
However, reading data which is in L1 gives the best results and works on most computers we have tested, this is why we ensure that the data is cached in the demos. 

Reading data which is not in L1 is slower, and if it is not cached at all it is a lot slower. Reading uncached memory might not work on all computers, as it also depends on the access latency of the DRAM. 

See also https://twitter.com/mlqxyz/status/950378419073712129 where we read a 40kb image using Meltdown (which is definitely larger than L1). 

You can also try to pin secret and physical_reader to different cores, so that they cannot share the L1 (L1 is private to each core). We tested this with all possible core combinations, and it also works.

**Comment by pRiVi** [comment]
I just did not see any code is able to fetch data which is not pushed all the time into Cache by reading. Maybe you're right, its not L1 but L3 - ok, but this donnot change that there is just no example to read inactive memory!

**Comment by misc0110** [comment]
As I said, this might not work on every computer with the current code (e.g., I can read uncached memory on my i7-6700K, but not on my i5-6200U, where I can only read cached memory). 
One experiment I did was to flush the memory in `secret` before reading it with `physical_reader`, to ensure that it is not cached in any cache. I was still able to read the memory contents, it was just slower.

**Comment by pRiVi** [comment]
I've tested the meltdown around here on many many manchines, no memory was readable which was not read all the time in endless loop.

This is my point, not if you try to flush and maybe read it then.

**Comment by dgruss** [comment]
can confirm that it works across cores on my machine. can anyone else confirm too?

**Comment by pRiVi** [comment]
dgruss: I can too, but not if I remove the reading loop.

**Comment by paboldin** [comment]
@dgruss works on my machine with the following victim code (and different speculative read code):
```
	victim[0] = 0xdeadbeafUL;

	getchar();
```

Machine is:
```
$ head /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
stepping	: 9
microcode	: 0x5e
cpu MHz		: 3521.362
cache size	: 6144 KB
physical id	: 0
```

All I had to do is add `sched_yield`. Apparently the i7 core pre-caches data or restores cache state.

**Comment by paboldin** [comment]
I was able to read memory from physically-mapped area while loading it with `bpf_probe_read` in a bpf-probe code attached to `tracepoint/sched/sched_task`. Constant access in a loop in this scenario only trashed and invalidated the caches, since the application has this data cached by his virtual memory, and kernel code caches it by physical mapped memory.

I think that all we need here is a gadget inside the kernel that pre-caches data or accesses them in other way. The `pagefault` handler seems to invalidate the cache in case of non-allowed access. I tested this with `recvfrom` which is not checking `buff` to be in userspace up to somewhere in 4.0 with no results.

**Comment by pRiVi** [comment]
Yes, and can you now tell me where this is covered in the meltdown paper?

**Comment by paboldin** [comment]
@pRiVi you mean mentioning `sched_yield`? It would expose the security vulnerability fully, so not telling about it was a right thing. I was expecting a gate to be some kind of buggy kernel code that loads data into the cache, only discovered `sched_yield` after reading https://github.com/mniip/spectre-meltdown-poc/blob/master/poc.c . This code might be even exploitable from browser's JavaScript.

I believe that modern Xeons are vulnerable this way as well. So keeping this information secret was a correct thing to do. Hiding these details also leaded to a little more hype so this issue got more media coverage so that everyone is going to update their systems.

**Comment by pRiVi** [comment]
I am just not understanding what you mean.

With sched_yield you can monitor a the unmodified secret.c, or the modified secrec.c without a loop?

**Comment by paboldin** [comment]
@pRiVi I can read data that I wrote *once* and is not referencing anymore at all, being stuck inside the glibc's `getch` function waiting for a symbol to arrive. All I had to do is to `sched_yield` into this code and it apparently speculates so far into userspace that it prefetches the secret, which is used again below.

All GUI applications read from X-server into the buffer in a loop, so this exploit will work on them.

**Comment by paboldin** [comment]
Guys, if the speculation reads the data into L1 cache, we can speculatively load the original data into the L1 cache using the same approach.

**Comment by pRiVi** [comment]
So you found a way on specific type programs with a specific loop (on a specific memory range of their memory?) to read ?

**Comment by paboldin** [comment]
@pRiVi yes. First, this is a very wide-spread approach, all GUI applications use it. Second, this does not mean there is no other ways to read memory.

**Comment by pRiVi** [comment]
@paboldin: Exactly. But again: This is not whats have been written in the meltdown paper. Not nearly!

**Comment by paboldin** [comment]
@pRiVi well, I believe that I just overestimated my expectations on the original exploit following the media hype around the vulnerability. Meltdown paper never claimed you can read any memory of any process without any preconditions. And hiding the preconditions were a right thing to do until the patches are out officially.

**Comment by pRiVi** [comment]
@paboldin No, it did!

> On such systems, an attacker can use Meltdown to dump the entire physical
> memory, simply by reading from virtual addresses starting
> at 0xffff 8800 0000 0000.

**Comment by Frichetten** [comment]
I'm sorry, can someone illuminate me? What is the significance of sched_yield?

**Comment by paboldin** [comment]
@pRiVi by at least at some machines you can 'simple read':
```
cached = 26, uncached = 235, threshold 78
read ffff96184000000b = 48 H (score=2/2)
read ffff96184000000b = 48 H (score=1/2)
read ffff96184000000a = e0   (score=2/2)
read ffff96184000000c = 8d   (score=1/2)
read ffff96184000000d = 86   (score=1/2)
read ffff96184000000e = 58 X (score=1/2)
read ffff96184000000c = 8d   (score=1/2)
read ffff96184000000e = 58 X (score=1/2)
```

**Comment by paboldin** [comment]
@Frichetten `sched_yield` (https://linux.die.net/man/2/sched_yield) says to kernel that the application has nothing to do and can give up processor at the moment. 

In meltdown attack it rises probability that the victim will be scheduled on the same CPU thus leaving it's data in the same L1-cache as we are. (Though this works even when victim and attacker run on different CPU packages, so it must be reading through some high-level cache like L2 or L3.)

The only things that are missing in this scenario are:
1. We read physical memory by it's identity mapping. This mapping never gets accessed by the original application. But L1 cache is virtually indexed physically tagged (VIPT), so it must be smart enough to detect reads from the same physical address (by another virtual address) and stupid enough to give us data speculatively.
2. Some CPUs are loading data into the L1 cache when scheduling the process even though it is not being accessed at the moment (see my ./victim.c above). This either is a result of deep out-of-order execution or of another optimization that pre-caches page table entries into L1 cache.

**Comment by misc0110** [comment]
There are already reports of other - independent - researchers who were able to read uncached memory, e.g. https://twitter.com/aionescu/status/950994906759143425

**Comment by BAM0S** [comment]
@pRiVi I insert your new code snippets to secret.c and build it:
```
  struct timeval tv; // after   libkdump_init(config);
...
// After sched_yield();
    printf("%s\n", secret);
    tv.tv_sec = 1;
    tv.tv_usec = 0;
    select(0,0,0,0,&tv);
```
Then I tried to read, but still I don't nothing :( 
Maybe I missed something.

**Comment by pRiVi** [comment]
BAMOS: The thing is not that my patch leads to be able to read. Current persons who can read can this only caused the loop inside of secret.c.

**Comment by paboldin** [comment]
@misc0110 I propose to leave this open, changing title to something like 'meltdown exploit preconditions' and marking it as a `discussion` via tag. There will be questions like this now and then and this will also stop duplicates.

**Comment by pRiVi** [comment]
@paboldin I donnot think you understand @misc0110 . There is no bug, its working on his machine so the whole world has a problem about meltdown.

**Comment by misc0110** [comment]
@paboldin good suggestion, but I'd rather open a new issue and add a FAQ section in the readme, discussing such things. This issue contains already too much unhelpful noise imo.

**Comment by paboldin** [comment]
@pRiVi It works on mine as well, with the code I wrote independently.

This is a huge security flaw, but of course the media overhyped again (https://smbc-comics.com/index.php?db=comics&id=1623).

It works on latest three generations of Intel's CPUs and there maybe like a few millions vulnerable machines. This is around a few billions of USD just in the cost of CPUs, w/o replacement.

**Comment by paboldin** [comment]
@misc0110 by the way, I think I should add a check for victim-reader pattern in my code and include the results in the output people are posting to the list.

**Comment by pRiVi** [comment]
@paboldin This is not the point. Of course is meltdown an big issue!

The meltdown paper is just incomplete or wrong in case of this things, and even the autors make PoCs tricking the user as if they computers were effected like painted in the paper. And this is just not the case!!!

**Comment by mlq** [comment]
@pRiVi Other people implemented their own PoCs to show that this attack is working. We uploaded our own PoC and other people are confirming (multiple times) that this PoC is working on their machine: https://twitter.com/aionescu/status/950994906759143425 - You are the only one who is apparently not capable of reproducing the results... 

Please stop wasting our time.

**Comment by BAM0S** [comment]
@mlq He is not the only one. I still don't succeed to reproduce. I used it on an Ubuntu machine I just installed. I tried to stress the CPU while doing it and still nothing.
Almost all the tests worked well but when it comes to read from the physical memory, I still don't see that it read it correctly.
I also disabled the KASLR and you can see closed issues for a problems.

I am not blaming them, maybe it not so easy to reproduce on every machine.

**Comment by pRiVi** [comment]
See https://meltdown-core-catcher.com/

**Comment by misc0110** [comment]
Ok, let me be clear here: Meltdown is a real bug, which can do exactly the things described in the paper, read arbitrary mapped memory. 

Now some more details which hopefully clarify a few things for you. 

 * Meltdown is a race condition. It is inherent to a race condition that it is not reliably reproducible. If we win the race condition, we can read memory, if we lose the race condition, we can't. 
 * There are many factors influencing the probability to win the race condition. We know of some factors, but there are possibly more. 
 * One of the factors is whether the memory is cached. The faster the access to the memory, the higher the probability to leak memory. Thus, memory in L1 cache is easier to leak than uncached memory. This is due to the time window of the race condition, which is quite small. 
 * Other factors are the speed of the CPU, the speed of the DRAM, the background activity on your system, the size of the reorder buffer, ...
 * These are all factors which could be handled in software to make the exploitation reliable. We explicitly don't do that, because it is a proof-of-concept implementation, not an exploit tool. People will write exploit tools, I have no doubt about that. 
 * Generalizing from your own experience is generally not considered scientific, especially when other (indepedent) researchers already reproduced our claims which prove you wrong.
 * Microarchitectural attacks (as Meltdown is) are often not easy to understand and reproduce. We tried our best to provide code which works for many people, but as the code does not rely on the defined architectural layer (as normal software does), it might behave a bit different on different machines. A small difference might already be enough that it appears to not, or not fully work anymore. This does not mean that there is no bug, it just means that this instance of the code does not work for this specific machine. Other researcher had similar issues, but if you understand how the bug (and the code) works, you can optimize the code (which we won't do) and/or tune some of the parameters. 
 * For some of my computers I also need a more optimized implementation of this code to read uncached memory. This is fine, it does not mean that the PoC, or the paper, or the bug itself is fake. If you really want to reliably read - for what reason ever - uncached memory, just take the code and optimize it to your needs. However, I won't help you with that, as I don't want other people to use Meltdown to exploit anything, especially not when not all systems are patched yet. 
 * And even if you could only read cached memory on some systems, there are ways to get uncached data into the cache from an unprivileged user program. We already did this, and my colleagues also described it in https://gruss.cc/files/prefetch.pdf

To summarize: Meltdown can read any memory, not only cached memory. We are not trying to trick people, just give them a starting point for their own experiments. It is no shame if you cannot reproduce the bug, we have a background in microarchitectural attacks as we focus our research on them for several years now, and even we have sometimes the problem of reproducing such PoCs on certain machines. 

I don't have a problem to discuss things on a scientific level, in fact I like such discussions. But your behaviour is not scientific at all - you ignore anything which does not fit into your view of the world. Bring me some facts, and I will happily discuss and check them. 

As a conclusion: Don't you think a company like Intel would immediately release a statement if our claims would be wrong?

**Comment by CaptainP21** [comment]
@misc0110 I just followed the discussion and have to say that your attitude is illogical.

In the Meltdown Paper you and your fellow students wrote: 

> 
Meltdown is not
only limited to reading kernel memory but it is capable
of reading the entire physical memory of the target machine.
> 

For this statement does not exist a proof of concept yet and both google and intel wrote that there is a precondition that the exploitable data is in L1 cache.

Intels paper: 

> 
The final method is the rogue data cache load. This method involves an application (user) attacker
directly probing kernel (supervisor) memory. Such an operation would typically result in a program
error (page fault due to page table permissions). However, it is possible for such an operation to be
speculatively executed under certain conditions for certain implementations. For instance, on some
implementations such a speculative operation will only pass data on to subsequent operations if the
data is resident in the lowest level data cache (L1). This can allow the data in question to be queried
by the application, leading to a side channel that reveals supervisor data. This method only applies to
regions of memory designated supervisor-only by the page tables; not memory designated as not
present. 
> 

This is not a proof of the assumption in the meltdown paper, that you could read the whole physical memory!

Your assumptions about reading uncached memory are unproofed and neither intel nor google 
support your assertion.

**Comment by Frichetten** [comment]
@pRiVi @CaptainP21 If I may jump in here, other researchers have shown they can reliably read non-L1 data. 
https://twitter.com/aionescu/status/951261470343360513
https://twitter.com/aionescu/status/950994906759143425

**Comment by misc0110** [comment]
@pRiVi So us showing a video and other researchers reproducing it (as also pointed out by @Frichetten) is no proof? Who is illogical here?

Jann, who originally discovered Meltdown, experimented with L1 data, this is why it is on the Google blog. His main focus was on Spectre as he has told us. This should not in anyway be considered as a critique of Jann's work - I think what he did was absolutely genius, without a doubt. In his presentation today he also said that leaking uncached memory is possible as we have shown that. Intel simply took the statement from Google. 

It is very simple to check that the statement that data has to be in L1 is incorrect: run the unmodified programs (which apparently work for you), and pin them to different CPU cores:

```
sudo taskset 0x1 ./secret
sudo taskset 0x2 ./physical_reader <address>
````
I'm very confident that this will work for you (maybe you need a different combination of cores though). And if it does, you proved yourself that it is not limited to the L1, because the L1 is private to each core. One core simply cannot access the L1 of a different core.

**Comment by paboldin** [comment]
@CaptainP21 I stated that I was able to read non L1-cached memory via independent code in a few first comments. I'm not sure if it "works" for everyone.

@misc0110 please start an issue-discussion with preconditions for the meltdown to read non-cached memory. Every day we postpone we lose time on arguing here.

**Comment by paboldin** [comment]
@dgruss Agree. Looking forward for the paper! Will it be an arxiv update first?

**Comment by pRiVi** [comment]
@misc0110 The only thing I have learned is how you treat others, who find them tricked by a loop never mentioned everywhere, without it is not working.
You do not go into this issue, instead you just go to

- I knew more you
- Someone did do something you cannot see

This is nothing for me that fits to critical rationalism or how we should work in public about issues like that.

That is also your stage about this thinks, and in my eyes you just failed here.

**Comment by CaptainP21** [comment]
@misc0110 @Frichetten @ dgruss @paboldin  I would like to believe you, but it's hard for me without a working proof of concept or a confirmation from another independent location.

Pinning the secret to an another core is for me not a proof that you could read the wohle physical memory as described in the meltdown paper. The secret in here in the L3 cache!

Imho a real proof could be:

1. writing the secret.
2. flushing the whole L1-L3 caches with some high load code for each core
3. proof that L1-L3 caches are flushed
4. reading the secret

**Comment by dgruss** [comment]
> I would like to believe you, but it's hard for me without a working proof of concept or a
> confirmation from another independent location.

No one here is asking anyone to *believe* anything. At this point, I personally would simply like to ask you to wait a
few more weeks until more sophisticated code will be published which will then also work on your systems.
I would ask you to wait until then and to defer any discussion to that point. It's clearly leading nowhere to carry out
the discussion right now when neither of us can (for completely valid reasons) provide the other one with more
information. The discussion cannot move onward from this. This is nonsensical and wastes your time as much as it wastes
ours, and this is in neither of our interest.

>  2. flushing the whole L1-L3 caches with some high load code for each core

That's not how caches work.

>  3. proof that L1-L3 caches are flushed

There's no way to prove that something is not in the cache without reloading the secret into the cache. Because that's
how caches work.

WRT to caches, you can check out these slides and talks for background information:
https://gruss.cc/files/cache_and_rowhammer_ruhrsec.pdf
https://www.youtube.com/watch?v=gxsguH5opsM&t=1574s&index=21&list=PLGwxVDXkP5UDE11zl4zWeQUr8EdrI9jZj
https://www.youtube.com/watch?v=cAWmNp3Ukqk&index=16&list=PLGwxVDXkP5UDE11zl4zWeQUr8EdrI9jZj
https://www.youtube.com/watch?v=iS8YPDuZbKM&index=13&list=PLGwxVDXkP5UDE11zl4zWeQUr8EdrI9jZj

I also provide a good amount of background information on caches in my thesis: https://gruss.cc/files/phd_thesis.pdf



Cheers,
Daniel

**Comment by rohan-0100010110010100** [comment]
@dgruss I'm a very new to low-level stuff can u please outline how this present version of the POC work and what will be improvement to this code in future if you guys are planning to discuss the criteria for winning race condition as described?

**Comment by dgruss** [comment]
On 12.01.2018 16:20, Rohan Verma wrote:
> @dgruss <https://github.com/dgruss> I'm a very new to low-level stuff can u please outline how this present version of
> the POC work and what will be improvement to this code in future if you guys are planning to discuss the criteria for
> winning race condition as described?

Cannot publicly talk about this at the moment.

**Comment by CaptainP21** [comment]
@dgruss excuse my impatience and my superficial knowledge how caches work.

i see proving the content of caches is nonsense (dunno if there is microcode support for such a thing), nvm but overwriting the caches with another physical adresses should be possible.

**Comment by dgruss** [comment]
On 12.01.2018 16:25, CaptainP21 wrote:
> @dgruss <https://github.com/dgruss> excuse my impatience and my superficial knowledge how caches work.
> 
> i see proving the content of caches is nonsense (dunno if there is microcode support for such a thing), nvm but
> overwriting the caches with another physical adresses should be possible.

Yes. See https://gruss.cc/files/rowhammerjs.pdf how to do that. Or use clflush...

**Comment by CaptainP21** [comment]
@dgruss You mean changing the secret.c code from
`  while (1) {
    // keep string cached for better results
    volatile size_t dummy = 0, i;
    for (i = 0; i < len; i++) {
      dummy += secret[i];
    }
    sched_yield();
  }`

to 

`while (1) {
    // keep cache flushed
    volatile size_t dummy = 0, i;
    for (i = 0; i < len; i++) {
      clflush((unsigned char*)secret[i]);
    }
    sched_yield();
  }`

and reading the secret afterwards should work on some machines, appending from dram timing?

**Comment by dgruss** [comment]
On 12.01.2018 17:00, CaptainP21 wrote:
> |while (1) { // keep cache flushed volatile size_t dummy = 0, i; for (i = 0; i < len; i++) { clflush((unsigned
> char*)secret[i]); } sched_yield(); }|
> 
> and reading the secret afterwards should work on some machines, appending from dram timing?

It does. Very stable and reliable across many(!) different machines. But you have to adapt the physical_reader for that.

**Comment by misc0110** [comment]
sched_yield() is not needed at all. This can also be seen in Video #5 and in the video of researcher Alex Ionescu (https://twitter.com/aionescu/status/951261470343360513).

**Comment by pRiVi** [comment]
Okay, interesting. But this is again working in direction which I think is not about this problem.

I think at all that a change to secret.c is not a vaild idea at all, because we want to read without help from the target.

**Comment by pRiVi** [comment]
@CaptainP21 I think we should differ here, my approach would be to clear at first if there is any read/write/flush/whatever needed to be able to read or not. For this scenario it is not a valid thing to do anything. After a result from that you can add actions an look what of them helps, and we can develop theories, make predictions and verify them.

On the other hand, this is what I understand you want to do, it is also an interesting thing how assumed actions of realworld programs already helps to be able to read from them. For this this scenario I think this is a valid idea - but this does not help about if it can work if the program is not helping at all, what - in my opinion - was the question on this bug entry.

If you do not care if a action is needed at all, that maybe push data into cache, then you also can resume to the test you mentioned. Or if you first want to clarify which one helps best at fast, it is the same.

**Comment by CaptainP21** [comment]
@pRiVi Honestly, I do not understand your point of view, any code writes to the cpu-caches at some point in time.

The question is whether the information to be read at the time of reading must be in the CPU cache.

**Comment by rohan-0100010110010100** [comment]
@dgruss  @misc0110 Apart from agreements and disagreements on the issue of the meltdown-POC this is the most informative thread that I've ever encountered  on github.On the account of using rowhammer attack, isn't this attack based upon the  quality of DRAM chips or vendor-specific DRAM chips ?

**Comment by pRiVi** [comment]
@CaptainP21 I completly agree with you, I do not thing that we have a different goal or idea what the issue is. Just the way I prefer to make this sure is different.
